### ISSUE TITLE
not installing correctly

### ISSUE THREAD

**Issue by hamidi19** [trenta-os/installation-script#8]
I have a Dell Vostro 1540 laptop. I had Blu linux and now installed Trenta (new install method).
After first reboot system could not load gui session so I logged into commandline terminal and loaded gui with "startx". I continued installation but there was not top and down pannel. Just desktop contained old blu stuff. Installation compeleted but nothing changed. It can not load gui session and can not load pannels.

**Comment by 19kestier** [comment]
You need to do a fresh install of Ubuntu 14.04, then run the Trenta Install scripts.
